#include "Pokemon.h"


CPokemon::CPokemon(int id)
{
	nombre = new char[20];
	switch (id)
	{
	/*case 1: nombre = "bulbasour", tipo = ; break;
	case 2: nombre = "Ivysaur", tipo = ; break;
	case 3: nombre = "Venusaur", tipo = ; break;
	case 4: nombre = "Charmander", tipo = ; break;
	case 5: nombre = "Charmeleon", tipo = ; break;
	case 6: nombre = "Charizard", tipo = ; break;
	case 7: nombre = "Squirtle", tipo = ; break;
	case 8: nombre = "Wartotle", tipo = ; break;
	case 9: nombre = "Blastoise", tipo = ; break;
	case 10: nombre = "Caterpie", tipo = ; break;
	case 11: nombre = "Metapod", tipo = ; break;
	case 12: nombre = "Butterfree", tipo = ; break;
	case 13: nombre = "Weedle", tipo = ; break;
	case 14: nombre = "Kakuna", tipo = ; break;
	case 15: nombre = "Beedrill", tipo = ; break;
	case 16: nombre = "Pidgey", tipo = ; break;
	case 17: nombre = "Pidgeotto", tipo = ; break;
	case 18: nombre = "Pidgeot", tipo = ; break;
	case 19: nombre = "Ratata", tipo = ; break;
	case 20: nombre = "Raticate", tipo = ; break;
	case 21: nombre = "Spearow", tipo = ; break;
	case 22: nombre = "Fearow", tipo = ; break;
	case 23: nombre = "Ekans", tipo = ; break;
	case 24: nombre = "Arbok", tipo = ; break;
	case 25: nombre = "Pikachu", tipo = ; break;
	case 26: nombre = "Raichu", tipo = ; break;
	case 27: nombre = "Sandshrew", tipo = ; break;
	case 28: nombre = "Sandlash", tipo = ; break;
	case 29: nombre = "Nidoran", tipo = ; break;
	case 30: nombre = "Nidorina", tipo = ; break;
	case 31: nombre = "Nidoqueen", tipo = ; break;
	case 32: nombre = "Nidoran", tipo = ; break;
	case 33: nombre = "Nidorino", tipo = ; break;
	case 34: nombre = "Nidoking", tipo = ; break;
	case 35: nombre = "Clefairy", tipo = ; break;
	case 36: nombre = "Clefable", tipo = ; break;
	case 37: nombre = "", tipo = ; break;
	case 38: nombre = "", tipo = ; break;
	case 39: nombre = "", tipo = ; break;
	case 40: nombre = "", tipo = ; break;
	case 41: nombre = "", tipo = ; break;
	case 42: nombre = "", tipo = ; break;
	case 43: nombre = "", tipo = ; break;
	case 44: nombre = "", tipo = ; break;
	case 45: nombre = "", tipo = ; break;
	case 46: nombre = "", tipo = ; break;
	case 47: nombre = "", tipo = ; break;
	case 48: nombre = "", tipo = ; break;
	case 49: nombre = "", tipo = ; break;
	case 50: nombre = "", tipo = ; break;
	case 51: nombre = "", tipo = ; break;
	case 52: nombre = "", tipo = ; break;
	case 53: nombre = "", tipo = ; break;
	case 54: nombre = "", tipo = ; break;
	case 55: nombre = "", tipo = ; break;
	case 56: nombre = "", tipo = ; break;
	case 57: nombre = "", tipo = ; break;
	case 58: nombre = "", tipo = ; break;
	case 59: nombre = "", tipo = ; break;
	case 60: nombre = "", tipo = ; break;
	case 61: nombre = "", tipo = ; break;
	case 62: nombre = "", tipo = ; break;
	case 63: nombre = "", tipo = ; break;
	case 64: nombre = "", tipo = ; break;
	case 65: nombre = "", tipo = ; break;
	case 66: nombre = "", tipo = ; break;
	case 67: nombre = "", tipo = ; break;
	case 68: nombre = "", tipo = ; break;
	case 69: nombre = "", tipo = ; break;
	case 70: nombre = "", tipo = ; break;
	case 71: nombre = "", tipo = ; break;
	case 72: nombre = "", tipo = ; break;
	case 73: nombre = "", tipo = ; break;
	case 74: nombre = "", tipo = ; break;
	case 75: nombre = "", tipo = ; break;
	case 76: nombre = "", tipo = ; break;
	case 77: nombre = "", tipo = ; break;
	case 78: nombre = "", tipo = ; break;
	case 79: nombre = "", tipo = ; break;
	case 80: nombre = "", tipo = ; break;
	case 81: nombre = "", tipo = ; break;
	case 82: nombre = "", tipo = ; break;
	case 83: nombre = "", tipo = ; break;
	case 84: nombre = "", tipo = ; break;
	case 85: nombre = "", tipo = ; break;
	case 86: nombre = "", tipo = ; break;
	case 87: nombre = "", tipo = ; break;
	case 88: nombre = "", tipo = ; break;
	case 89: nombre = "", tipo = ; break;
	case 90: nombre = "", tipo = ; break;
	case 91: nombre = "", tipo = ; break;
	case 92: nombre = "", tipo = ; break;
	case 93: nombre = "", tipo = ; break;
	case 94: nombre = "", tipo = ; break;
	case 95: nombre = "", tipo = ; break;
	case 96: nombre = "", tipo = ; break;
	case 97: nombre = "", tipo = ; break;
	case 98: nombre = "", tipo = ; break;
	case 99: nombre = "", tipo = ; break;
	case 100: nombre = "", tipo = ; break;
	case 101: nombre = "", tipo = ; break;
	case 102: nombre = "", tipo = ; break;
	case 103: nombre = "", tipo = ; break;
	case 104: nombre = "", tipo = ; break;
	case 105: nombre = "", tipo = ; break;
	case 106: nombre = "", tipo = ; break;
	case 107: nombre = "", tipo = ; break;
	case 108: nombre = "", tipo = ; break;
	case 109: nombre = "", tipo = ; break;
	case 110: nombre = "", tipo = ; break;
	case 111: nombre = "", tipo = ; break;
	case 112: nombre = "", tipo = ; break;
	case 113: nombre = "", tipo = ; break;
	case 114: nombre = "", tipo = ; break;
	case 115: nombre = "", tipo = ; break;
	case 116: nombre = "", tipo = ; break;
	case 117: nombre = "", tipo = ; break;
	case 118: nombre = "", tipo = ; break;
	case 119: nombre = "", tipo = ; break;
	case 120: nombre = "", tipo = ; break;
	case 121: nombre = "", tipo = ; break;
	case 122: nombre = "", tipo = ; break;
	case 123: nombre = "", tipo = ; break;
	case 124: nombre = "", tipo = ; break;
	case 125: nombre = "", tipo = ; break;
	case 126: nombre = "", tipo = ; break;
	case 127: nombre = "", tipo = ; break;
	case 128: nombre = "", tipo = ; break;
	case 129: nombre = "", tipo = ; break;
	case 130: nombre = "", tipo = ; break;
	case 131: nombre = "", tipo = ; break;
	case 132: nombre = "", tipo = ; break;
	case 133: nombre = "", tipo = ; break;
	case 134: nombre = "", tipo = ; break;
	case 135: nombre = "", tipo = ; break;
	case 136: nombre = "", tipo = ; break;
	case 137: nombre = "", tipo = ; break;
	case 138: nombre = "", tipo = ; break;
	case 139: nombre = "", tipo = ; break;
	case 140: nombre = "", tipo = ; break;
	case 141: nombre = "", tipo = ; break;
	case 142: nombre = "", tipo = ; break;
	case 143: nombre = "", tipo = ; break;
	case 144: nombre = "", tipo = ; break;
	case 145: nombre = "", tipo = ; break;
	case 146: nombre = "", tipo = ; break;
	case 147: nombre = "", tipo = ; break;
	case 148: nombre = "", tipo = ; break;
	case 149: nombre = "", tipo = ; break;
	case 150: nombre = "", tipo = ; break;*/
		
	}
}


CPokemon::~CPokemon()
{
}
void CPokemon::CrearPokemon(){

}
void CPokemon::Pintar(){
	Bitmap ^img;
	switch (id)
	{
	case 1: img = gcnew Bitmap("imagen/pokedex/001.png"); break;
	case 2: img = gcnew Bitmap("imagen/pokedex/002.png"); break;
	case 3: img = gcnew Bitmap("imagen/pokedex/003.png"); break;
	case 4: img = gcnew Bitmap("imagen/pokedex/004.png"); break;
	case 5: img = gcnew Bitmap("imagen/pokedex/005.png"); break;
	case 6: img = gcnew Bitmap("imagen/pokedex/006.png"); break;
	case 7: img = gcnew Bitmap("imagen/pokedex/007.png"); break;
	case 8: img = gcnew Bitmap("imagen/pokedex/008.png"); break;
	case 9: img = gcnew Bitmap("imagen/pokedex/009.png"); break;
	case 10: img = gcnew Bitmap("imagen/pokedex/010.png"); break;
	case 11: img = gcnew Bitmap("imagen/pokedex/011.png"); break;
	case 12: img = gcnew Bitmap("imagen/pokedex/012.png"); break;
	case 13: img = gcnew Bitmap("imagen/pokedex/013.png"); break;
	case 14: img = gcnew Bitmap("imagen/pokedex/014.png"); break;
	case 15: img = gcnew Bitmap("imagen/pokedex/015.png"); break;
	case 16: img = gcnew Bitmap("imagen/pokedex/016.png"); break;
	case 17: img = gcnew Bitmap("imagen/pokedex/017.png"); break;
	case 18: img = gcnew Bitmap("imagen/pokedex/018.png"); break;
	case 19: img = gcnew Bitmap("imagen/pokedex/019.png"); break;
	case 20: img = gcnew Bitmap("imagen/pokedex/020.png"); break;
	case 21: img = gcnew Bitmap("imagen/pokedex/021.png"); break;
	case 22: img = gcnew Bitmap("imagen/pokedex/022.png"); break;
	case 23: img = gcnew Bitmap("imagen/pokedex/023.png"); break;
	case 24: img = gcnew Bitmap("imagen/pokedex/024.png"); break;
	case 25: img = gcnew Bitmap("imagen/pokedex/025.png"); break;
	case 26: img = gcnew Bitmap("imagen/pokedex/026.png"); break;
	case 27: img = gcnew Bitmap("imagen/pokedex/027.png"); break;
	case 28: img = gcnew Bitmap("imagen/pokedex/028.png"); break;
	case 29: img = gcnew Bitmap("imagen/pokedex/029.png"); break;
	case 30: img = gcnew Bitmap("imagen/pokedex/030.png"); break;
	case 31: img = gcnew Bitmap("imagen/pokedex/031.png"); break;
	case 32: img = gcnew Bitmap("imagen/pokedex/032.png"); break;
	case 33: img = gcnew Bitmap("imagen/pokedex/033.png"); break;
	case 34: img = gcnew Bitmap("imagen/pokedex/034.png"); break;
	case 35: img = gcnew Bitmap("imagen/pokedex/035.png"); break;
	case 36: img = gcnew Bitmap("imagen/pokedex/036.png"); break;
	case 37: img = gcnew Bitmap("imagen/pokedex/037.png"); break;
	case 38: img = gcnew Bitmap("imagen/pokedex/038.png"); break;
	case 39: img = gcnew Bitmap("imagen/pokedex/039.png"); break;
	case 40: img = gcnew Bitmap("imagen/pokedex/040.png"); break;
	case 41: img = gcnew Bitmap("imagen/pokedex/041.png"); break;
	case 42: img = gcnew Bitmap("imagen/pokedex/042.png"); break;
	case 43: img = gcnew Bitmap("imagen/pokedex/043.png"); break;
	case 44: img = gcnew Bitmap("imagen/pokedex/044.png"); break;
	case 45: img = gcnew Bitmap("imagen/pokedex/045.png"); break;
	case 46: img = gcnew Bitmap("imagen/pokedex/046.png"); break;
	case 47: img = gcnew Bitmap("imagen/pokedex/047.png"); break;
	case 48: img = gcnew Bitmap("imagen/pokedex/048.png"); break;
	case 49: img = gcnew Bitmap("imagen/pokedex/049.png"); break;
	case 50: img = gcnew Bitmap("imagen/pokedex/050.png"); break;
	case 51: img = gcnew Bitmap("imagen/pokedex/051.png"); break;
	case 52: img = gcnew Bitmap("imagen/pokedex/052.png"); break;
	case 53: img = gcnew Bitmap("imagen/pokedex/053.png"); break;
	case 54: img = gcnew Bitmap("imagen/pokedex/054.png"); break;
	case 55: img = gcnew Bitmap("imagen/pokedex/055.png"); break;
	case 56: img = gcnew Bitmap("imagen/pokedex/056.png"); break;
	case 57: img = gcnew Bitmap("imagen/pokedex/057.png"); break;
	case 58: img = gcnew Bitmap("imagen/pokedex/058.png"); break;
	case 59: img = gcnew Bitmap("imagen/pokedex/059.png"); break;
	case 60: img = gcnew Bitmap("imagen/pokedex/060.png"); break;
	case 61: img = gcnew Bitmap("imagen/pokedex/061.png"); break;
	case 62: img = gcnew Bitmap("imagen/pokedex/062.png"); break;
	case 63: img = gcnew Bitmap("imagen/pokedex/063.png"); break;
	case 64: img = gcnew Bitmap("imagen/pokedex/064.png"); break;
	case 65: img = gcnew Bitmap("imagen/pokedex/065.png"); break;
	case 66: img = gcnew Bitmap("imagen/pokedex/066.png"); break;
	case 67: img = gcnew Bitmap("imagen/pokedex/067.png"); break;
	case 68: img = gcnew Bitmap("imagen/pokedex/068.png"); break;
	case 69: img = gcnew Bitmap("imagen/pokedex/069.png"); break;
	case 70: img = gcnew Bitmap("imagen/pokedex/070.png"); break;
	case 71: img = gcnew Bitmap("imagen/pokedex/071.png"); break;
	case 72: img = gcnew Bitmap("imagen/pokedex/072.png"); break;
	case 73: img = gcnew Bitmap("imagen/pokedex/073.png"); break;
	case 74: img = gcnew Bitmap("imagen/pokedex/074.png"); break;
	case 75: img = gcnew Bitmap("imagen/pokedex/075.png"); break;
	case 76: img = gcnew Bitmap("imagen/pokedex/076.png"); break;
	case 77: img = gcnew Bitmap("imagen/pokedex/077.png"); break;
	case 78: img = gcnew Bitmap("imagen/pokedex/078.png"); break;
	case 79: img = gcnew Bitmap("imagen/pokedex/079.png"); break;
	case 80: img = gcnew Bitmap("imagen/pokedex/080.png"); break;
	case 81: img = gcnew Bitmap("imagen/pokedex/081.png"); break;
	case 82: img = gcnew Bitmap("imagen/pokedex/082.png"); break;
	case 83: img = gcnew Bitmap("imagen/pokedex/083.png"); break;
	case 84: img = gcnew Bitmap("imagen/pokedex/084.png"); break;
	case 85: img = gcnew Bitmap("imagen/pokedex/085.png"); break;
	case 86: img = gcnew Bitmap("imagen/pokedex/086.png"); break;
	case 87: img = gcnew Bitmap("imagen/pokedex/087.png"); break;
	case 88: img = gcnew Bitmap("imagen/pokedex/088.png"); break;
	case 89: img = gcnew Bitmap("imagen/pokedex/089.png"); break;
	case 90: img = gcnew Bitmap("imagen/pokedex/090.png"); break;
	case 91: img = gcnew Bitmap("imagen/pokedex/091.png"); break;
	case 92: img = gcnew Bitmap("imagen/pokedex/092.png"); break;
	case 93: img = gcnew Bitmap("imagen/pokedex/093.png"); break;
	case 94: img = gcnew Bitmap("imagen/pokedex/094.png"); break;
	case 95: img = gcnew Bitmap("imagen/pokedex/095.png"); break;
	case 96: img = gcnew Bitmap("imagen/pokedex/096.png"); break;
	case 97: img = gcnew Bitmap("imagen/pokedex/097.png"); break;
	case 98: img = gcnew Bitmap("imagen/pokedex/098.png"); break;
	case 99: img = gcnew Bitmap("imagen/pokedex/099.png"); break;
	case 100: img = gcnew Bitmap("imagen/pokedex/100.png"); break;
	case 101: img = gcnew Bitmap("imagen/pokedex/101.png"); break;
	case 102: img = gcnew Bitmap("imagen/pokedex/102.png"); break;
	case 103: img = gcnew Bitmap("imagen/pokedex/103.png"); break;
	case 104: img = gcnew Bitmap("imagen/pokedex/104.png"); break;
	case 105: img = gcnew Bitmap("imagen/pokedex/105.png"); break;
	case 106: img = gcnew Bitmap("imagen/pokedex/106.png"); break;
	case 107: img = gcnew Bitmap("imagen/pokedex/107.png"); break;
	case 108: img = gcnew Bitmap("imagen/pokedex/108.png"); break;
	case 109: img = gcnew Bitmap("imagen/pokedex/109.png"); break;
	case 110: img = gcnew Bitmap("imagen/pokedex/110.png"); break;
	case 111: img = gcnew Bitmap("imagen/pokedex/111.png"); break;
	case 112: img = gcnew Bitmap("imagen/pokedex/112.png"); break;
	case 113: img = gcnew Bitmap("imagen/pokedex/113.png"); break;
	case 114: img = gcnew Bitmap("imagen/pokedex/114.png"); break;
	case 115: img = gcnew Bitmap("imagen/pokedex/115.png"); break;
	case 116: img = gcnew Bitmap("imagen/pokedex/116.png"); break;
	case 117: img = gcnew Bitmap("imagen/pokedex/117.png"); break;
	case 118: img = gcnew Bitmap("imagen/pokedex/118.png"); break;
	case 119: img = gcnew Bitmap("imagen/pokedex/119.png"); break;
	case 120: img = gcnew Bitmap("imagen/pokedex/120.png"); break;
	case 121: img = gcnew Bitmap("imagen/pokedex/121.png"); break;
	case 122: img = gcnew Bitmap("imagen/pokedex/122.png"); break;
	case 123: img = gcnew Bitmap("imagen/pokedex/123.png"); break;
	case 124: img = gcnew Bitmap("imagen/pokedex/124.png"); break;
	case 125: img = gcnew Bitmap("imagen/pokedex/125.png"); break;
	case 126: img = gcnew Bitmap("imagen/pokedex/126.png"); break;
	case 127: img = gcnew Bitmap("imagen/pokedex/127.png"); break;
	case 128: img = gcnew Bitmap("imagen/pokedex/128.png"); break;
	case 129: img = gcnew Bitmap("imagen/pokedex/129.png"); break;
	case 130: img = gcnew Bitmap("imagen/pokedex/130.png"); break;
	case 131: img = gcnew Bitmap("imagen/pokedex/131.png"); break;
	case 132: img = gcnew Bitmap("imagen/pokedex/132.png"); break;
	case 133: img = gcnew Bitmap("imagen/pokedex/133.png"); break;
	case 134: img = gcnew Bitmap("imagen/pokedex/134.png"); break;
	case 135: img = gcnew Bitmap("imagen/pokedex/135.png"); break;
	case 136: img = gcnew Bitmap("imagen/pokedex/136.png"); break;
	case 137: img = gcnew Bitmap("imagen/pokedex/137.png"); break;
	case 138: img = gcnew Bitmap("imagen/pokedex/138.png"); break;
	case 139: img = gcnew Bitmap("imagen/pokedex/139.png"); break;
	case 140: img = gcnew Bitmap("imagen/pokedex/140.png"); break;
	case 141: img = gcnew Bitmap("imagen/pokedex/141.png"); break;
	case 142: img = gcnew Bitmap("imagen/pokedex/142.png"); break;
	case 143: img = gcnew Bitmap("imagen/pokedex/143.png"); break;
	case 144: img = gcnew Bitmap("imagen/pokedex/144.png"); break;
	case 145: img = gcnew Bitmap("imagen/pokedex/145.png"); break;
	case 146: img = gcnew Bitmap("imagen/pokedex/146.png"); break;
	case 147: img = gcnew Bitmap("imagen/pokedex/147.png"); break;
	case 148: img = gcnew Bitmap("imagen/pokedex/148.png"); break;
	case 149: img = gcnew Bitmap("imagen/pokedex/149.png"); break;
	case 150: img = gcnew Bitmap("imagen/pokedex/150.png"); break;
	}

}